### ISSUE TITLE
Refactor ParThreadsafe to use secret-superclass

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#111]
"Secret superclass" is a better design pattern than this current business of using an `unsafeParIO` method, which we make sure the user cannot instance themselves.

Should be real easy to solve this because `unsafeParIO` uses can just be replaced with `internalLiftIO`.  And it removes the confusing redundancy between those two.

**Comment by osa1** [comment]
Hm, I'm confused about how this is supposed to work. If we define 'ParThreadSafeSecret` in a non-exported module in `par-classes` we can't implement `ParThreadSafe` at all, because `par-classes` doesn't implement any instances. If we export `ParThreadSafeSecret` in `par-classes`, then users can implement instances.

**Comment by rrnewton** [comment]
The distinction is between `Control.Par.Class` (SafeHaskell Trustworthy), and `Control.Par.Class.Unsafe` (SafeHaskell Unsafe).

The user *can* get to everything with the unsafe module, but they lose SafeHaskell Safe (inferred) status.
